function event = gen_event( pop_size, group_size )
% Generate an event for my learning simulation
% 
% Generates an event. First generates index of a member of popb.
% Then generates an index of a member of popa. 
%
% Each popb member belongs to a group (measured by its index-1 div 
% group_size) and generates numbers for indices in its group and the 
% next group. Thus with a group size of 3, population b member number 20 
% is in group 6 and generates numbers between 19 and 24 inclusive. The 
% highest group generates numbers for the lowest so if the population only
% had 20 members, member 20 would generate numbers 19,20,1,2,3.

% Calculate the maximum group number
max_group = floor((pop_size-1) / group_size);

% Calculate b's group 
b_index = randi(pop_size,1);
b_group = floor((b_index-1)/group_size); % 0 based group number
b_next_group = mod(b_group+1,max_group+1);

% Calculate lower and upper bounds on the legal indices in b's group and
% the next group
a_lb1 = b_group*group_size+1;
a_ub1 = min((b_group+1)*group_size, pop_size);
a_lb2 = b_next_group*group_size+1;
a_ub2 = min((b_next_group+1)*group_size, pop_size);

% Select a random index from the legal ones generated by b
a_indices = mod(([a_lb1:a_ub1 a_lb2:a_ub2])-1,pop_size)+1;
a_index = a_indices(randi(size(a_indices),1));

event=[a_index, b_index];

end

